name: 'Install PNPM'
description: 'Install PNPM'

inputs:
  pnpm-version:
    description: 'The version of PNPM to use'
    required: false
    default: '8'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Get pnpm store directory
      id: pnpm-store-path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      id: cache-hit
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: steps.cache-hit.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install
