name: 'Cache PNPM'
description: 'Cache PNPM'

inputs:
  include-cache:
    description: 'Include the cache in the workflow.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Get pnpm store directory
      id: pnpm-store-path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - if: ${{ inputs.include-cache == 'true' }}
      name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
