name: 'Create Test Coverage Comment'
description: 'Create a comment on a pull request with the test coverage report'

inputs:
  github-token:
    description: 'The GitHub token'
    required: true

runs:
  using: 'node20'
  main: '../../dist/upsert-test-coverage-comment/index.js'
