name: Reusable versioning

on:
  workflow_call:
    inputs:
      release-command-execution:
        default: false
        description: 'Specify whether to execute the release command. If set to true, the release command will be executed; otherwise, it will be skipped.'
        type: boolean
        required: false
    secrets:
      github-token:
        description: 'A token passed from the caller workflow'
        required: true

env:
  repository-owner: ${{ github.repository_owner }}
  repository-name: ${{ github.event.repository.name }}
  pull-request-number: ${{ github.event.pull_request.number }}
  username: ${{ github.event.pull_request.merged_by.login }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: philipseo/actions
          path: ./.github/reusable-actions

      - name: Install Node.js
        uses: ./.github/reusable-actions/actions/install-node

      - name: Run Versioning
        shell: bash
        run: npx -p @philipseo/scripts versioning ${{ secrets.github-token }} ${{ env.repository-owner }} ${{ env.repository-name }} ${{ env.pull-request-number }}

      - name: Install PNPM Dependencies
        uses: ./.github/reusable-actions/actions/install-pnpm

      - name: Run prettier:fix
        shell: bash
        run: pnpm prettier:fix

      - name: Version Update Commit
        run: |
          git config user.name "${{ env.username }}"
          git config user.email "${{ env.username }}@users.noreply.github.com"
          git add .
          git commit -m 'Release'
          git push origin main --force

      - name: Release
        if: ${{ inputs.release-command-execution == 'true' }}
        shell: bash
        run: pnpm release

      - name: Create Github Release
        shell: bash
        run: npx -p @philipseo/scripts create-github-release ${{ secrets.github-token }} ${{ env.repository-owner }} ${{ env.repository-name }}
