name: reusable lint workflow

on:
  workflow_call:
    inputs:
      lint-command:
        default: 'pnpm lint'
        description: 'The lint command to run'
        type: string
        required: false
    secrets:
      GH_TOKEN:
        description: 'The GitHub token to use'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install PNPM Dependencies
        uses: philipseo/actions/.github/actions/install-pnpm-dependencies/action.yml@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Run Linting
        shell: bash
        run: ${{ inputs.lint-command }}