name: pnpm build

on:
  workflow_call:
    inputs:
      pnpm-version:
        type: string
        description: 'The version of pnpm to use'
        required: false
      node-version:
        type: string
        description: 'The version of Node.js to use'
        required: false
      include-cache:
        type: string
        description: 'Include the cache in the workflow.'
        required: false
      pnpm-install-args:
        type: string
        description: 'The arguments to pass to the pnpm install command.'
        required: false
      build-command:
        type: string
        description: 'The command to build the project'
        required: false
        default: 'pnpm build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node, pnpm and dependencies
        uses: ./actions/install-pnpm
        with:
          pnpm-version: ${{ inputs.pnpm-version }}
          node-version: ${{ inputs.node-version }}
          include-cache: ${{ inputs.include-cache }}
          pnpm-install-args: ${{ inputs.pnpm-install-args }}

      - name: Build
        shell: bash
        run: ${{ inputs.build-command }}
