name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-check:
    name: Reusable PR Check
    uses: ./.github/workflows/reusable-pr-check.yml@${{ github.event.ref }}
    with:
      is-local: true
