name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run lint
        shell: bash
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run Build upsetTestCoverageComment
        shell: bash
        run: pnpm build:upsert-test-coverage-comment

      - name: Run Test
        shell: bash
        run: pnpm test:coverage

      - name: Upsert Test Coverage Comment
        uses: ./actions/upsert-test-coverage-comment
        with:
          github-token: ${{ secrets.GH_TOKEN }}
  failed-slack-notify:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run Build slackNotify
        shell: bash
        run: pnpm build:slack-notify

      - name: Slack notify2
        uses: ./actions/slack-notify
        with:
          title: 'Failed PR Check'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
