name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#env:
#  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
#  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable PR Check
        uses: philipseo/actions/.github/workflows/reusable-pr-check.yml@main
        with:
          is-local: true
          reusable-actions-folder-path: './actions'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
