name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run lint
        shell: bash
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run Test
        uses: ./actions/changed-since-test-coverage

      - name: Upsert Test Coverage Comment
        uses: ./actions/upsert-test-coverage-comment
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  new-version-comment:
    if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Upsert Test Coverage Comment
        uses: ./actions/upsert-new-version-comment
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  failed-slack-notify:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [lint, test, new-version-comment]
    steps:
      - name: Checkout code Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Slack notify
        uses: ./actions/slack-notify
        with:
          title: 'Failed PR Check'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
