name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run lint
        shell: bash
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run Build
        shell: bash
        run: pnpm build

      - name: Run Test
        shell: bash
        run: pnpm test

      - name: Create test Coverage Comment
        shell: bash
        run: ./actions/create-test-coverage-comment

  failed-slack-notify:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code Repository
        uses: actions/checkout@v4

      - name: Slack notify2
        uses: ./actions/slack-notify
        with:
          title: 'Failed PR Check'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          extends-section-fields: |
            [
              {
                "type": "mrkdwn",
                "text": "*Workflow*: <${{ github.repositoryUrl }}/actions/runs/${{ github.run_id }}|link>"
              }
            ]
