name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-check:
    name: Reusable PR Check
    uses: ./.github/workflows/reusable-pr-check.yml
    with:
      reusable-lint-path: './.github/workflows/reusable-lint.yml'
      reusable-test-path: './.github/workflows/reusable-test.yml'
