name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run lint
        shell: bash
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Run test
        shell: bash
        run: pnpm test

  slack-notify:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code Repository
        uses: actions/checkout@v4

      - name: Slack notify
        uses: ./actions/slack-notify
        with:
          title: 'Test :rocket:'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}

      - name: Slack notify2
        uses: ./actions/slack-notify
        with:
          title: 'Test :rocket:'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          extends-section-fields: |
            [
              {
                "type": "mrkdwn",
                "text": "test1"
              },
              {
                "type": "mrkdwn",
                "text": "test2"
              }
            ]
