name: PR Check

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Reusable PR Check
    uses: ./.github/workflows/reusable-pr-check.yml
    with:
      is-local: true
      reusable-actions-folder-path: './.github/workflows'
