name: Reusable lint

on:
  workflow_call:
    inputs:
      is-local:
        default: false
        description: 'Is local'
        type: boolean
        required: false
      reusable-actions-folder-path:
        default: './.github/reusable-actions/actions'
        description: 'The path to the folder containing reusable actions. When running the workflow locally, specify the path to the folder containing reusable actions.'
        type: string
        required: false
      test-command:
        default: 'pnpm test'
        description: 'The test command to run'
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        if: ${{ !inputs.is-local }}
        uses: actions/checkout@v4
        with:
          repository: philipseo/actions
          path: ${{ inputs.reusable-actions-folder-path }}

      - name: Install Node.js
        uses: ${{ inputs.reusable-actions-folder-path }}/install-node

      - name: Install PNPM Dependencies
        uses: ${{ inputs.reusable-actions-folder-path }}/install-pnpm

      - name: Run Test
        shell: bash
        run: ${{ inputs.test-command }}
