name: Reusable PR Check

on:
  workflow_call:
    inputs:
      reusable-lint-path:
        default: 'philipseo/actions/.github/workflows/reusable-lint.yml@main'
        description: 'Boolean flag indicating whether the workflow is running locally or within GitHub Actions environment.'
        type: string
        required: false
      reusable-test-path:
        default: 'philipseo/actions/.github/workflows/reusable-test.yml@main'
        description: 'Boolean flag indicating whether the workflow is running locally or within GitHub Actions environment.'
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Reusable lint
    uses: ${{ inputs.reusable-lint-path }}
#
#  test:
#    runs-on: ubuntu-latest
#    needs: [lint]
#    steps:
#      - name: Reusable test
#        uses: ${{ inputs.reusable-action-folder-path }}/workflows/reusable-test
#        with:
#          is-local: ${{ inputs.is-local }}
#          reusable-action-folder-path: ${{ inputs.reusable-action-folder-path }}
#          test-commend: ${{ inputs.lint-commend }}

#  slack-notify:
#    runs-on: ubuntu-latest
#    needs: [lint, test]
#    steps:
#      - name: Checkout code Repository
#        uses: actions/checkout@v4
#
#      - name: Slack notify
#        uses: ./actions/slack-notify
#        with:
#          title: 'Test :rocket:'
#          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
#          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
#          extends-section-fields: |
#            [
#              {
#                type: 'mrkdwn',
#                text: 'test1',
#              },
#              {
#                type: 'mrkdwn',
#                text: 'test2',
#              }
#            ]
