name: Reusable versioning workflow

on:
  workflow_call:
    inputs:
      github-token:
        description: 'The github token to use'
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repository-owner: ${{ github.event.repository_owner }}
  repository-name: ${{ github.event.repository.name }}
  pull-request-number: ${{ github.event.pull_request.number }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: philipseo/actions
          path: reusable-actions

      - name: Install Node.js
        uses: ./reusable-actions/actions/install-node

      - name: Run Versioning
        shell: bash
        run: npx @philipseo/scripts versioning ${{ inputs.githubToken }} ${{ env.repository-owner }} ${{ env.repository-name }} ${{ env.pull-request-number }}
