name: Reusable test

on:
  workflow_call:
    inputs:
      is-local:
        default: false
        description: 'Boolean flag indicating whether the workflow is running locally or within GitHub Actions environment.'
        type: boolean
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Checkout
#        if: ${{ !inputs.is-local }}
#        uses: actions/checkout@v4
#        with:
#          repository: philipseo/actions
#          path: ${{ inputs.reusable-actions-folder-path }}
#
#      - name: Install Node.js
#        uses: ${{ inputs.reusable-actions-folder-path }}/install-node
#
#      - name: Install PNPM Dependencies
#        uses: ${{ inputs.reusable-actions-folder-path }}/install-pnpm
#
#      - name: Run Test
#        shell: bash
#        run: ${{ inputs.test-command }}
