name: Reusable lint workflow

on:
  workflow_call:
    inputs:
      lint-commend:
        default: 'pnpm lint'
        description: 'The lint command to run'
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: philipseo/actions
          path: reusable-actions

      - name: Install Node.js
        uses: ./reusable-actions/actions/install-node

      - name: Install PNPM Dependencies
        uses: ./reusable-actions/actions/install-pnpm

      - name: Run Linting
        shell: bash
        run: ${{ inputs.lint-commend }}
