name: Reusable lint

on:
  workflow_call:
    inputs:
      is-local:
        default: false
        description: 'Boolean flag indicating whether the workflow is running locally or within GitHub Actions environment.'
        type: boolean
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        if: ${{ !inputs.is-local }}
        uses: actions/checkout@v4
        with:
          repository: philipseo/actions
          path: ${{ inputs.reusable-action-folder-path }}

      - name: Install Node.js
        uses: ${{ inputs.reusable-action-folder-path }}/actions/install-node

      - name: Install PNPM Dependencies
        uses: ${{ inputs.reusable-action-folder-path }}/actions/install-pnpm

      - name: Run lint
        shell: bash
        run: ${{ inputs.lint-command }}
