name: PR Check

on:
  workflow_call:
    inputs:
      is-local:
        default: false
        description: 'Is local'
        type: boolean
        required: false
      reusable-actions-folder-path:
        default: './.github/reusable-actions'
        description: 'The path to the folder containing reusable actions'
        type: string
        required: false
      lint-commend:
        default: 'pnpm lint'
        description: 'The lint command to run'
        type: string
        required: false
      test-command:
        default: 'pnpm test'
        description: 'The test command to run'
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#env:
#  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
#  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable lint
        uses: ${{ inputs.reusable-action-folder-path }}/workflows/reusable-lint
        with:
          is-local: ${{ inputs.is-local }}
          reusable-action-folder-path: ${{ inputs.reusable-action-folder-path }}
          lint-commend: ${{ inputs.lint-commend }}
#
#  test:
#    runs-on: ubuntu-latest
#    needs: [lint]
#    steps:
#      - name: Reusable test
#        uses: ${{ inputs.reusable-action-folder-path }}/workflows/reusable-test
#        with:
#          is-local: ${{ inputs.is-local }}
#          reusable-action-folder-path: ${{ inputs.reusable-action-folder-path }}
#          test-commend: ${{ inputs.lint-commend }}

#  slack-notify:
#    runs-on: ubuntu-latest
#    needs: [lint, test]
#    steps:
#      - name: Checkout code Repository
#        uses: actions/checkout@v4
#
#      - name: Slack notify
#        uses: ./actions/slack-notify
#        with:
#          title: 'Test :rocket:'
#          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
#          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
#          extends-section-fields: |
#            [
#              {
#                type: 'mrkdwn',
#                text: 'test1',
#              },
#              {
#                type: 'mrkdwn',
#                text: 'test2',
#              }
#            ]
