name: Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: ./actions/install-node

      - name: Install PNPM Dependencies
        uses: ./actions/install-pnpm

      - name: Update Version And Upsert CHANGELOG.md
        uses: ./actions/update-version-and-changelog

      - name: Run prettier:fix
        shell: bash
        run: pnpm prettier:fix

      - name: Version Update Commit And Push
        run: |
          git config user.name "${{ env.username }}"
          git config user.email "${{ env.username }}@users.noreply.github.com"
          git add .
          git commit -m 'Release ${{ steps.versioning.outputs.new-version }}'
          git push origin main --force

      #      - name: Create Github Release
      #        uses: ./actions/create-github-release
      #        run: npx -p @philipseo/scripts create-github-release ${{ secrets.github-token }} ${{ env.repository-owner }} ${{ env.repository-name }}

      - name: Success Slack notify
        if: ${{ success() }}
        uses: ./actions/slack-notify
        with:
          title: 'Release ${{ steps.versioning.outputs.new-version }}'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}

      - name: Failed Slack notify
        if: ${{ failure() }}
        uses: ./actions/slack-notify
        with:
          title: 'Failed Versioning'
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
